hello: hello.c
	gcc -fopenmp hello.c -o hello

vector-addition: vector-addition.c
	gcc -fopenmp vector-addition.c -o vector-addition

dot-product: dot-product.c
	gcc -fopenmp dot-product.c -o dot-product

work-sharing: work-sharing.c
	gcc -fopenmp work-sharing.c -o work-sharing

